### ISSUE TITLE
100-step-rewards

### ISSUE THREAD

**Issue by remingtr** [adulbrich/osu-fsf#103]
**Title**: Implement Logarithmic Reward Thresholds and Customizable Icons for Step Tracking Event

**Body**:

### Description
We need to enhance our step tracking event app by allowing event organizers to set up reward thresholds in a logarithmic manner. This will involve creating functionality for defining step thresholds and associating each threshold with a specific reward icon, which can be uploaded by the organizer. This feature will motivate participants by clearly defining the goals and visually representing the rewards.

### Requirements
1. **Admin Interface for Reward Configuration**:
   - Implement a user interface in the admin panel that allows event organizers to define and edit reward thresholds and associated icons.
   
2. **Logarithmic Thresholds**:
   - Support for setting up at least three reward thresholds. Example starting thresholds might be set as follows:
     - **Reward 1 Threshold**: 3,000 steps
     - **Reward 2 Threshold**: 7,000 steps
     - **Reward 3 Threshold**: 13,000 steps
   - These thresholds should follow a logarithmic scale by default but allow the organizer to edit them as needed.

3. **Uploadable Icons**:
   - Allow organizers to upload an icon for each reward threshold.
   - Ensure compatibility with common image formats (e.g., JPG, PNG).

4. **User Interface Considerations**:
   - Provide immediate visual feedback for uploaded icons and successful data entry.

6. **Backend Implementation**:
   - Adjust the database schema to accommodate storing the new threshold and icon data.
   - Implement backend logic to handle creation, retrieval, updating, and deletion of the reward threshold data.

### User Story
As an event organizer, I want to be able to set specific step thresholds for rewards in a logarithmic scale and upload icons representing each reward, so that participants have clear, visually engaging goals to strive towards during the competition.

### Acceptance Criteria
- [ ] The admin can access a reward configuration page from the dashboard.
- [ ] Organizers can set and edit thresholds and upload corresponding icons through a simple form.
- [ ] Thresholds and icons update in real-time on the participant interface once saved.
- [ ] Proper validations are in place to prevent the submission of incorrect data formats.
- [ ] All data is stored securely and is retrievable for editing.

**Comment by chungyu1108** [comment]
done
