### ISSUE TITLE
Happy flow for an FSF event participant

### ISSUE THREAD

**Issue by adulbrich** [adulbrich/osu-fsf#18]
Describe in a step-by-step process, including a diagram, what the "happy flow" could mean for an FSF member participating in an event, starting with registering for an event all the way to getting a reward for being in the best team.

This will help set the direction for #17 and the corresponding Figma prototype

**Comment by fuenteed** [comment]
Happy Flow

User views the events available: After the user open the application, they are showed a page with upcoming events that they can sign up for in an organized list form. They are shown with the following information: the day it stars, days they occur, time they occur, as well as the location.

User selects the event: They decide to click the "Walktober" event which begins on October 1st. The user would like to participate with their department team that they made.

User views the event details: After the user clicks the button, a screen is shown with a description of the event, as well as a register button. Which they end up clicking.

User checks their calendar: After the user has successfully registered for the event, they can now see it on their calendar.

User checks other teams: Additionally, once registered for the event, the user can check out other teams participating in this event. 

User begins to participate in the event: The user then starts a fitness session and walks 2 miles, the application will automatically track the distance the user travels. After the user is done, they stop the fitness session and see their progress. 

User checks the progress of the event: The user can open up their team on the application to check their progress in whatever form that takes (steps, distance, wins/losses, etc.) They can also check the progress of other FSF teams. This page shows the team members, their individual progress on the event, as well as the cumulative progress made by the entire team. 

User wins the league: After some time of participating in Walktober, the user and their team are the team that have traveled the farthest distance. Their department which made the team, got rewarded with trophies as well as each member receiving their own running care package that includes a nike gift card, a vest that holds water bottles, pre-run boost powders, and a running shirt to encourage them to stay physically healthy.
