### ISSUE TITLE
Happy flow for an FSF organizer

### ISSUE THREAD

**Issue by adulbrich** [adulbrich/osu-fsf#19]
Describe in a step-by-step process, including a diagram, what the "happy flow" could mean for an FSF organizer creating a new event and running that event, from the creation of the event until it's completion.

Will help set the direction for #16 and the corresponding Figma prototype

**Comment by remingtr** [comment]
Happy flows for Back office front end

Nicole wants to create a new event: Nicole opens up the webpage for the back office.  She sees “create event” at the bottom middle of the screen.  She is redirected to another screen where she will type in the event description, start date, and end date.  She will then click on a "create" button that sends the event info to the database, which will be presented in the mobile app.  (There will be more inputs once we meet with someone at Ideal-Logic)

Nicole wants to see user activity stats: Nicole will open up the webpage, navigate to "current event", and then be brought to a screen that shows statistics on how many active participants, total accumulated steps for all users, and a leaderboard for the current teams.

Nicole wants to edit an event: Nicole will open up the webpage, navigate to “current event”, then she will click on edit event, and then she will be brought to a screen where she can edit all of the attributes she inputted when she created an event.  

Nicole wants to send an announcement: Nicole will open the webpage, navigate to "announcements" on the drawer tab, then she will be taken to a screen that shows the previous announcements and a button that says "new announcement".  She clicks on "new announcement" and is brought to a page with a text box.   Nicole will type the announcement into the text box, and then click "Send Announcement".  

Nicole wants to edit an announcement: Nicole will open the webpage, navigate to announcements where she will see a list of previous announcements, and then she will click on a pencil icon that is attached to the announcement.  The text box inside the announcement becomes writeable and she will be able to edit it as she pleases. After she is finished she will click "done" and the announcement will be viewable on the mobile app.

**Comment by remingtr** [comment]
![Image](https://github.com/OregonStateUniversity/osu-fsf/assets/102546859/b47cddf8-d513-4dec-9726-c7825e021e13)

**Comment by adulbrich** [comment]
Nice job, unsure about how announcements will work in practice: 
- event-specific or audience-wide?
- what happens on the end-user side when an announcement is updated?
