### ISSUE TITLE
Access Analytics on Events

### ISSUE THREAD

**Issue by remingtr** [adulbrich/osu-fsf#31]
This story is quite large and covers too many things, let's re-write it later to cover either:
- As an organizer, I want to generate reports on event participation, such as total steps walked, active participants, and team rankings.
- As an organizer, I want to access analytics on user engagement to improve future events.

Part of Epic 4 of #16 

### User Story Statement: 

As an FSF event organizer, I want to view the previous events, so that I can see a history of user activity over the past 2 years.  

### Background

 **_Why do we want it?_** We want this feature because FSF event organizers need a way to see the performance of a previous event so that they can make better decisions based on their past experience.  

**_Who is this for?_** This is for event organizers and not users.  

**_Do we have the data to support it?_** Yes, we have verified that this feature is vital to FSF organizers.  

### Solution/Requirements

Functional Requirements: 

- User should be able to view a list of previous events
- User should be able to view user activity for all previous events

- User should be able to filter events by year

Non-functional Requirements

- Data for an event should be stored in the database indefinitely unless there is a reason for deletion
- Back-office should be able to display data for an event within 1 second after clicking on it
- The data attached to a previous event should never be changeable

### Design Resources
[Figma Design Board](https://www.figma.com/file/47YJ1KtmES10TIdGPuF6EZ/OSU-Fitness-App?type=design&node-id=0%3A1&mode=design&t=k3no0PKV7BbD2epr-1)

### Dependencies

_**Are we waiting on other user stories or tasks to be completed?**_  Yes, we have some other user stories to complete.   The homepage still needs to be created so that the event organizer can click on "events."  

_**Are other user stories or tasks waiting on this issue to be completed?**_  Yes, this user story is blocking one other user story.  "As an event organizer, I want to be able to import past events, so that I can easily start a new event without retyping the same information." This story requires that the "View Previous Events" feature is available.  

### List of tasks and subtasks

- [ ]  Initialize backend https://github.com/OregonStateUniversity/osu-fsf/issues/15
- [ ] Creation of events  https://github.com/OregonStateUniversity/osu-fsf/issues/21
- [ ] Initialize database
- [ ] Connect database to back office
- [ ]  Initialize webpage
- [ ]  Add "events" button to homepage
- [ ]  Save event data after event creation
- [ ]  Collect user activity data and store in database
- [ ]  Create events page
- [ ]  Display event data when event clicked on

### Estimate

I estimate each sub-task to take a week.  Some will take longer than others, but the completion of all of these tasks will be near the last half of the project's completion.  

### Open Questions

- What user data will we store?
- Will events be in the database permanently?
- Will users see past events?

### Acceptance Criteria

- Given a user clicks on "events", the list of previous events will be displayed
- Given a user clicks on an event, the event data will be displayed
- Given a user creates an event, the event information is saved in database

### Definition of Done

- [ ] All code passes linting checks
- [ ] All code passes unit/integration tests
- [ ] Fulfills all functional and non-functional requirements
- [ ] Covers all acceptance criteria
- [ ] All subtasks listed are completed
- [ ] User should be able to view previous events, click on events, and see data for that event

**Comment by chungyu1108** [comment]
check
