### ISSUE TITLE
Identify in the app via email or similar

### ISSUE THREAD

**Issue by traveno** [adulbrich/osu-fsf#32]
### User story statement

> As a event participant, I want to be able to uniquely identify myself to the mobile application, so that I can effectively track my stats across more than one event.

### Background

* Why do we want it?
End users need to be able to track their stats across more than a single event. This provides more meaningful stats that both the end user and back office user may analyze.
* Who is this for?
Applicable for end users, and may be analyzed by both the end user and the back office user(s).
* Do we have data to support it?
Assuming we are able to successfully track end user fitness, yes! The data will be available to make this happen. We haven't picked an end user auth method yet (to uniquely identify our users across events) but that will be coming up soon.

### Solution / Requirements

* A auth method in the mobile app allowing unique identification
* Password / account recovery support
* Simple and easy for end users to use
* The same (or similar) auth method provided for the back office application

### Design Resources

* Our mobile / web figma flows, but design will be arbitrary because it highly depends on which auth method we end up picking

### Dependencies

* Blocked by #6 (schema supports authenticated profiles, but have yet to pick auth service)

### Tasks / Subtasks

1. Pick applicable auth method (possibly for both mobile / back office) [1 day]
2. Add auth method support to Supabase [1 day]
3. Add login form to mobile application [1 day]
4. Allow mobile user authentication (appropriate database rows accessible) [1 week]
5. Allow back office user authentication (appropriate database rows accessible) [1 week]

### Estimate

* Approximately 2 weeks of time, several tasks can be in progress simultaneously.

### Open Questions

* How complicated will be allow the auth system to be? We have options such as native mobile auth, SSO, etc. Many users will be older and non-students: therefore, we keep it as simple as can possibly be? Open for debate.

### Acceptance Criteria
 
1. Mobile / web applications both have auth forms that prevent access until completed
2. Appropriate database tables / rows are accessible by both types of accounts (end user / back office user)

### Definition of Done (DoD)

Authenticating with the application consequently shows stats / abilities appropriate for that account type. Account information is carried over between login sessions.

**Comment by adulbrich** [comment]
What about starting with the default email auth?
