### ISSUE TITLE
Research backend technology

### ISSUE THREAD

**Issue by adulbrich** [adulbrich/osu-fsf#4]
Consider https://supabase.com/ to get started quickly, otherwise look into more traditional ways of doing a backend (e.g., Node) or more modern things like Rust.

Some inspiration: https://survey.stackoverflow.co/2023/#technology

**Comment by fuenteed** [comment]
Looking over Rust frameworks for backend, knowing that we were talking about using an SQL related database. Rust has a library for directly working with SQL databases called SQLx. 
Here is the documentation for it : https://docs.rs/sqlx/latest/sqlx/

**Comment by fuenteed** [comment]
https://medium.com/geekculture/building-backend-web-with-supabase-45eb8a97cdd7 
Reading this article it seems like Supabase would be very convenient as it acts as a Backend as a platform Server(BaaS) where we can directly create our database, implement user authentication and more without the need of an external service.

**Comment by adulbrich** [comment]
For the MVP, we'll use Supabase and its library
