### ISSUE TITLE
Refactored Home Page

### ISSUE THREAD

**Issue by fuenteed** [adulbrich/osu-fsf#96]
**Background**
This refactored home page currently displays the following: 

- A list of all the events that the signed in user is participating in. Within each event section are the following: 

> 1.  The team name of the user.
> 2. The total score of the team of the user.
> 3. A list of the teammates and their individual score for that given event.

**Implementation**
The home page currently is operating as a react functional component. This component merely displays the aforementioned information in a vertical list format without any styling. It is correctly pulling information from the database. 

**Tasks**
- [ Create A Figma Design of the Refactored Page]
- [Implement the Design in React Native]  
- [Utilize React Native Styling to make the page look more lively and responsive]

**Comment by chungyu1108** [comment]
done
